#!/usr/bin/env python3
"""
synthesise.py
Reads every transcript in /transcripts/, sends each to Claude API for
structured SEO tip extraction, aggregates results, counts frequency,
and saves to /outputs/raw_synthesis.md.

Requires: ANTHROPIC_API_KEY in environment or .env file
"""

import json
import os
import sys
import time
from pathlib import Path

import anthropic
from dotenv import load_dotenv

load_dotenv()

TRANSCRIPTS_DIR = Path(__file__).parent.parent / "transcripts"
OUTPUTS_DIR     = Path(__file__).parent.parent / "outputs"
OUTPUTS_DIR.mkdir(exist_ok=True)

RAW_OUTPUT = OUTPUTS_DIR / "raw_synthesis.md"

MODEL      = "claude-sonnet-4-6"
MAX_TOKENS = 4096

SYSTEM_PROMPT = """You are an SEO expert. Extract every actionable SEO recommendation from this transcript.
For each tip output:
- The recommendation (1-2 sentences, plain English)
- Theme: one of [technical], [content], [backlinks], [local], [ux]
- How important this is on a scale of 1-10
Return as a JSON array only, no other text. Example format:
[
  {
    "recommendation": "Submit your sitemap to Google Search Console so Google can find and index your pages faster.",
    "theme": "technical",
    "importance": 9
  }
]"""


def extract_tips(client: anthropic.Anthropic, transcript: str, filename: str) -> list[dict]:
    """Send a transcript to Claude and return a list of tip dicts."""
    print(f"  Sending to Claude API ({len(transcript):,} chars) ...")

    # Truncate very long transcripts to stay within token limits
    if len(transcript) > 80_000:
        transcript = transcript[:80_000]
        print(f"  (truncated to 80,000 chars)")

    try:
        message = client.messages.create(
            model=MODEL,
            max_tokens=MAX_TOKENS,
            system=SYSTEM_PROMPT,
            messages=[
                {
                    "role": "user",
                    "content": f"Here is the transcript:\n\n{transcript}"
                }
            ]
        )
        raw = message.content[0].text.strip()

        # Strip markdown code fences if present
        if raw.startswith("```"):
            raw = "\n".join(raw.splitlines()[1:])
        if raw.endswith("```"):
            raw = "\n".join(raw.splitlines()[:-1])

        tips = json.loads(raw)
        if not isinstance(tips, list):
            print(f"  WARNING: unexpected response format, skipping")
            return []
        return tips

    except json.JSONDecodeError as e:
        print(f"  ERROR: failed to parse JSON response — {e}")
        return []
    except anthropic.APIError as e:
        print(f"  ERROR: API error — {e}")
        return []


def normalise_tip(tip: dict, source_file: str) -> dict:
    """Ensure tip has expected fields, add source."""
    return {
        "recommendation": str(tip.get("recommendation", "")).strip(),
        "theme":          str(tip.get("theme", "")).lower().strip("[]"),
        "importance":     int(tip.get("importance", 5)),
        "sources":        [source_file],
    }


def aggregate_tips(all_tips: list[dict]) -> list[dict]:
    """
    Deduplicate tips by similarity (exact recommendation match for now),
    merge sources, and add a frequency score.
    """
    merged: dict[str, dict] = {}

    for tip in all_tips:
        key = tip["recommendation"].lower().strip()
        if key in merged:
            existing = merged[key]
            # Add source if not already listed
            for src in tip["sources"]:
                if src not in existing["sources"]:
                    existing["sources"].append(src)
            # Keep the highest importance score seen
            existing["importance"] = max(existing["importance"], tip["importance"])
        else:
            merged[key] = tip.copy()

    result = list(merged.values())
    for tip in result:
        tip["frequency"] = len(tip["sources"])

    return sorted(result, key=lambda t: (-t["frequency"], -t["importance"]))


def write_output(aggregated: list[dict], per_file_tips: dict[str, list[dict]]) -> None:
    """Write raw_synthesis.md with per-file breakdown and aggregated list."""
    lines = []
    lines.append("# Raw SEO Synthesis\n")
    lines.append(f"_Generated by synthesise.py — {len(aggregated)} unique tips from {len(per_file_tips)} transcripts_\n")

    # --- Per-transcript breakdown ---
    lines.append("\n---\n")
    lines.append("## Per-Transcript Extractions\n")
    for filename, tips in per_file_tips.items():
        lines.append(f"\n### {filename}  ({len(tips)} tips)\n")
        for tip in tips:
            theme      = tip.get("theme", "unknown")
            importance = tip.get("importance", "?")
            rec        = tip.get("recommendation", "")
            lines.append(f"- **[{theme}]** (importance: {importance}) {rec}\n")

    # --- Aggregated tips ---
    lines.append("\n---\n")
    lines.append("## Aggregated Tips (sorted by frequency then importance)\n")
    lines.append(f"\n| # | Theme | Freq | Imp | Recommendation |\n")
    lines.append(  "|---|-------|------|-----|----------------|\n")
    for i, tip in enumerate(aggregated, 1):
        rec   = tip["recommendation"].replace("|", "-")
        lines.append(
            f"| {i} | {tip['theme']} | {tip['frequency']} | {tip['importance']} | {rec} |\n"
        )

    # --- JSON dump for step 5 ---
    lines.append("\n---\n")
    lines.append("## JSON Data (used by checklist generator)\n")
    lines.append("```json\n")
    lines.append(json.dumps(aggregated, indent=2))
    lines.append("\n```\n")

    RAW_OUTPUT.write_text("".join(lines), encoding="utf-8")
    print(f"\nSaved: {RAW_OUTPUT}  ({RAW_OUTPUT.stat().st_size:,} bytes)")


def main():
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        print("ERROR: ANTHROPIC_API_KEY not set. Add it to your .env file.")
        sys.exit(1)

    client = anthropic.Anthropic(api_key=api_key)

    transcript_files = sorted(TRANSCRIPTS_DIR.glob("*.txt"))
    if not transcript_files:
        print(f"No transcripts found in {TRANSCRIPTS_DIR}")
        sys.exit(1)

    print(f"Found {len(transcript_files)} transcript(s)\n")

    per_file_tips: dict[str, list[dict]] = {}
    all_tips: list[dict] = []

    for path in transcript_files:
        print(f"[{path.name}]")
        text = path.read_text(encoding="utf-8").strip()

        if len(text) < 100:
            print(f"  SKIP: transcript too short ({len(text)} chars)\n")
            continue

        raw_tips = extract_tips(client, text, path.name)
        print(f"  Extracted {len(raw_tips)} tips")

        normalised = [normalise_tip(t, path.name) for t in raw_tips]
        per_file_tips[path.name] = normalised
        all_tips.extend(normalised)

        # Brief pause to avoid rate limiting
        time.sleep(1)
        print()

    if not all_tips:
        print("No tips extracted. Check transcript content and API key.")
        sys.exit(1)

    print("Aggregating tips ...")
    aggregated = aggregate_tips(all_tips)
    print(f"  {len(all_tips)} raw tips → {len(aggregated)} unique tips after deduplication\n")

    write_output(aggregated, per_file_tips)

    print("\n" + "=" * 60)
    print(f"SUMMARY")
    print("=" * 60)
    print(f"  Transcripts processed : {len(per_file_tips)}")
    print(f"  Raw tips extracted    : {len(all_tips)}")
    print(f"  Unique tips           : {len(aggregated)}")
    print(f"  Output                : {RAW_OUTPUT}")


if __name__ == "__main__":
    main()
